import { eventBus } from "../../../shared/domain/event-bus";

export { eventBus };

export enum DomainEvents {
  // USER
  USER_CREATED = "USER_CREATED",
  USER_ACTIVATED = "USER_ACTIVATED",
  USER_DEACTIVATED = "USER_DEACTIVATED",
  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
  ROLE_ASSIGNED = "ROLE_ASSIGNED",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  ACCOUNT_UNLOCKED = "ACCOUNT_UNLOCKED",

  // PROJECTS
  PROJECT_ASSIGNED = "PROJECT_ASSIGNED",
  PROJECT_STATUS_UPDATED = "PROJECT_STATUS_UPDATED",
  PROJECT_COMPLETED = "PROJECT_COMPLETED",

  // TASKS
  TASK_ASSIGNED = "TASK_ASSIGNED",
  TASK_COMPLETED = "TASK_COMPLETED",
  TASK_OVERDUE = "TASK_OVERDUE",
  TASK_COMMENT_ADDED = "TASK_COMMENT_ADDED",

  // WORKFLOW
  APPROVAL_REQUESTED = "APPROVAL_REQUESTED",
  APPROVAL_COMPLETED = "APPROVAL_COMPLETED",
  APPROVAL_REJECTED = "APPROVAL_REJECTED",

  // AUDIT
  CRITICAL_SECURITY_EVENT = "CRITICAL_SECURITY_EVENT",
}
